[build]
  # Directory to run the build command in
  base = "."
  
  # Build command
  command = "yarn build-storybook"
  
  # Directory with the static files to deploy
  publish = "storybook-static"

[build.environment]
  # Node version for build - Updated to 20 for Storybook 9.0.16 compatibility
  NODE_VERSION = "20"
  
  # Yarn version
  YARN_VERSION = "1.22.22"

# Redirect rules for Storybook routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optional: Branch deploys for preview
[context.deploy-preview]
  command = "yarn build-storybook"

[context.branch-deploy]
  command = "yarn build-storybook" 